name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create LocalGovDrupal project
        run: composer create-project --stability dev localgovdrupal/localgov-project html

      - name: Build container
        run: docker-compose build

      - name: Start Docker environment
        run: docker-compose up -d
      
      - name: Ensure everything is up to date
        run: docker exec -u docker -t drupal bash -c "cd /var/www/html && composer install"
      
      - name: Check coding standards
        run: docker exec -t drupal bash -c "cd /var/www/html && ./bin/phpcs"
      
      - name: Check for deprecated code
        run: docker exec -t drupal bash -c "cd /var/www/html && ./bin/phpstan analyse -c ./phpstan.neon ./web/profiles/contrib/localgov/ ./web/modules/contrib/localgov_*"
      
      - name: Running tests
        run: |
          docker exec -t drupal bash -c "mkdir -p /var/www/html/web/sites/simpletest && chmod 777 /var/www/html/web/sites/simpletest"
          docker exec -u docker -t drupal bash -c "cd /var/www/html && ./bin/phpunit --testdox"
