name: Test LocalGovDrupal

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Start Docker environment
        run: docker-compose up -d

      - name: Create LocalGov Drupal project
        run: docker exec -u docker -t drupal bash -c "mkdir -p /var/www/html && /usr/local/bin/composer create-project --stability dev localgovdrupal/localgov-project /var/www/html"

      - name: Run tests
        run: ./run-tests.sh
        shell: bash
